<?php

namespace AppBundle\Repository;

/**
 * UserStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
