# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.hangman_context:
        class:     AppBundle\GameContext
        arguments: ['@session']
    app.hangman_word_service:
        class:     AppBundle\Service\WordService
        arguments: ['@doctrine.orm.entity_manager']    
    app.hangman_stats_service:
        class:     AppBundle\Service\GameStatsService
        arguments: ['@doctrine.orm.entity_manager']    
